/**
 * Ported from Restyle (commit dfab2fea903923e4a19171cc4a2eb4cf4144d8ae)
 * src/types/definitions.ts — FieldMeta, GroupMeta, and PROMPT_GROUPS.
 *
 * Adaptations from restyle source:
 * - condition uses PromptSchema from ./prompt-schema (type-only import)
 * - t(locale, 'select_placeholder') inlined as 'Select…'
 * - FieldInput.type retains full union including 'select'
 */

import type { PromptSchema } from "./prompt-schema";

export type FieldMeta = {
  key: string;
  label: string;
  description: string;
  type: "text" | "textarea" | "color" | "number" | "select" | "tags" | "toggle";
  options?: string[];
  placeholder?: string;
};

export type GroupMeta = {
  key: string;
  label: string;
  icon: string;
  description: string;
  fields: FieldMeta[];
  condition?: (schema: PromptSchema) => boolean;
};

// ============================================================
// PROMPT_GROUPS — 15 groups, 98 fields
// ============================================================

export const PROMPT_GROUPS: GroupMeta[] = [
  {
    key: "subject",
    label: "Subject",
    icon: "🎯",
    description: "Main subject of the image",
    fields: [
      {
        key: "main_subject",
        label: "Main Subject",
        description: "The primary subject",
        type: "textarea",
        placeholder:
          "e.g., a young woman, a vintage camera, a mountain landscape",
      },
      {
        key: "quantity",
        label: "Quantity",
        description: "Number of subjects",
        type: "text",
        placeholder: "e.g., single, two, a group of",
      },
      {
        key: "subject_details",
        label: "Details",
        description: "Additional details about the subject",
        type: "textarea",
        placeholder: "e.g., wearing a red dress, with intricate engravings",
      },
      {
        key: "size_scale",
        label: "Size / Scale",
        description: "Size or scale of the subject",
        type: "text",
        placeholder: "e.g., life-size, miniature, gigantic",
      },
      {
        key: "orientation_placement",
        label: "Orientation / Placement",
        description: "Position in frame",
        type: "text",
        placeholder: "e.g., centered, off to the right, in the foreground",
      },
    ],
  },
  {
    key: "subject_character",
    label: "Character Details",
    icon: "🧑",
    description: "Character/animal-specific attributes",
    condition: (s) => ["character", "animal"].includes(s.subject_type),
    fields: [
      {
        key: "pose_action",
        label: "Pose / Action",
        description: "Body pose or action",
        type: "text",
        placeholder:
          "e.g., standing confidently, running, sitting cross-legged",
      },
      {
        key: "expression_emotion",
        label: "Expression / Emotion",
        description: "Facial expression or emotion",
        type: "text",
        placeholder: "e.g., mysterious smile, intense gaze, laughing",
      },
      {
        key: "clothing_accessories",
        label: "Clothing & Accessories",
        description: "Outfit and accessories",
        type: "textarea",
        placeholder: "e.g., leather jacket, neon earrings, silver watch",
      },
      {
        key: "body_features",
        label: "Body Features",
        description: "Physical features",
        type: "text",
        placeholder: "e.g., athletic build, tall, cybernetic arm",
      },
      {
        key: "hair_style",
        label: "Hair Style",
        description: "Hair description",
        type: "text",
        placeholder: "e.g., long flowing red hair, short undercut, braided",
      },
      {
        key: "age_appearance",
        label: "Age / Appearance",
        description: "Age and general appearance",
        type: "text",
        placeholder: "e.g., young adult, elderly, teenage",
      },
      {
        key: "ethnicity_skin_tone",
        label: "Ethnicity / Skin Tone",
        description: "Skin tone or ethnicity",
        type: "text",
        placeholder: "e.g., dark skin, pale, olive-toned",
      },
    ],
  },
  {
    key: "subject_object",
    label: "Object Details",
    icon: "📦",
    description: "Object/product-specific attributes",
    condition: (s) =>
      ["object", "product", "food", "vehicle"].includes(s.subject_type),
    fields: [
      {
        key: "object_state",
        label: "State",
        description: "Current state of the object",
        type: "text",
        placeholder: "e.g., brand new, in motion, half-eaten",
      },
      {
        key: "object_condition",
        label: "Condition",
        description: "Physical condition",
        type: "text",
        placeholder: "e.g., pristine, weathered, rusty",
      },
      {
        key: "brand_label",
        label: "Brand / Label",
        description: "Brand or label",
        type: "text",
        placeholder: "e.g., Leica, Apple, generic",
      },
      {
        key: "arrangement_layout",
        label: "Arrangement",
        description: "How the object is arranged",
        type: "text",
        placeholder: "e.g., flat lay, stacked, scattered",
      },
      {
        key: "interaction",
        label: "Interaction",
        description: "Interaction with other elements",
        type: "text",
        placeholder: "e.g., hand holding it, floating, resting on a surface",
      },
    ],
  },
  {
    key: "environment",
    label: "Environment",
    icon: "🌍",
    description: "Setting and background",
    fields: [
      {
        key: "setting",
        label: "Setting",
        description: "Main setting",
        type: "textarea",
        placeholder: "e.g., rain-soaked city street, enchanted forest, studio",
      },
      {
        key: "location_type",
        label: "Location Type",
        description: "Type of location",
        type: "text",
        placeholder: "e.g., indoor, outdoor, underwater, space",
      },
      {
        key: "time_of_day",
        label: "Time of Day",
        description: "Time of day",
        type: "text",
        placeholder: "e.g., golden hour, midnight, dawn",
      },
      {
        key: "weather",
        label: "Weather",
        description: "Weather conditions",
        type: "text",
        placeholder: "e.g., heavy rain, foggy, clear sky, snowing",
      },
      {
        key: "season",
        label: "Season",
        description: "Season",
        type: "text",
        placeholder: "e.g., autumn, summer, winter",
      },
      {
        key: "era_time_period",
        label: "Era / Time Period",
        description: "Historical period",
        type: "text",
        placeholder: "e.g., 1920s, medieval, futuristic",
      },
      {
        key: "background_elements",
        label: "Background Elements",
        description: "Background details",
        type: "textarea",
        placeholder: "e.g., holographic billboards, mountains, stars",
      },
      {
        key: "foreground_elements",
        label: "Foreground Elements",
        description: "Foreground details",
        type: "text",
        placeholder: "e.g., puddles, fallen leaves, steam",
      },
      {
        key: "ground_surface",
        label: "Ground Surface",
        description: "Ground description",
        type: "text",
        placeholder: "e.g., wet cobblestone, grass, sand dunes",
      },
      {
        key: "sky_description",
        label: "Sky",
        description: "Sky description",
        type: "text",
        placeholder: "e.g., dramatic sunset, starry night, overcast",
      },
    ],
  },
  {
    key: "composition",
    label: "Composition",
    icon: "📐",
    description: "Framing and camera setup",
    fields: [
      {
        key: "framing",
        label: "Framing",
        description: "Shot framing",
        type: "text",
        placeholder: "e.g., close-up, medium shot, full body, wide shot",
      },
      {
        key: "camera_angle",
        label: "Camera Angle",
        description: "Angle of view",
        type: "text",
        placeholder: "e.g., low angle, eye level, bird's eye, dutch angle",
      },
      {
        key: "perspective",
        label: "Perspective",
        description: "Perspective type",
        type: "text",
        placeholder: "e.g., one-point, fish-eye, isometric",
      },
      {
        key: "depth_of_field",
        label: "Depth of Field",
        description: "DOF setting",
        type: "text",
        placeholder: "e.g., shallow DOF, deep focus, tilt-shift",
      },
      {
        key: "focal_point",
        label: "Focal Point",
        description: "What is in focus",
        type: "text",
        placeholder: "e.g., subject's eyes, center of frame",
      },
      {
        key: "composition_rule",
        label: "Composition Rule",
        description: "Composition guideline",
        type: "text",
        placeholder: "e.g., rule of thirds, golden ratio, centered",
      },
      {
        key: "symmetry",
        label: "Symmetry",
        description: "Symmetry type",
        type: "text",
        placeholder: "e.g., symmetric, asymmetric, radial",
      },
      {
        key: "negative_space",
        label: "Negative Space",
        description: "Use of empty space",
        type: "text",
        placeholder: "e.g., lots of negative space, minimal, crowded",
      },
      {
        key: "crop_style",
        label: "Crop Style",
        description: "Cropping style",
        type: "text",
        placeholder: "e.g., tight crop, loose crop, full frame",
      },
    ],
  },
  {
    key: "lighting",
    label: "Lighting",
    icon: "💡",
    description: "Light sources and effects",
    fields: [
      {
        key: "primary_light_source",
        label: "Primary Light Source",
        description: "Main light",
        type: "text",
        placeholder: "e.g., sunlight, neon signs, candle, studio light",
      },
      {
        key: "light_direction",
        label: "Light Direction",
        description: "Where light comes from",
        type: "text",
        placeholder: "e.g., side lighting, backlighting, overhead",
      },
      {
        key: "light_quality",
        label: "Light Quality",
        description: "Quality of light",
        type: "text",
        placeholder: "e.g., soft, harsh, diffused, dappled",
      },
      {
        key: "light_color_temperature",
        label: "Color Temperature",
        description: "Warm or cool light",
        type: "text",
        placeholder: "e.g., warm 3200K, cool 6500K, mixed",
      },
      {
        key: "shadow_type",
        label: "Shadow Type",
        description: "Type of shadows",
        type: "text",
        placeholder: "e.g., deep contrast, soft, ambient occlusion",
      },
      {
        key: "shadow_intensity",
        label: "Shadow Intensity",
        description: "How strong the shadows are",
        type: "text",
        placeholder: "e.g., subtle, dramatic, none",
      },
      {
        key: "special_lighting_effects",
        label: "Special Effects",
        description: "Special lighting effects",
        type: "text",
        placeholder: "e.g., volumetric, god rays, lens flare, caustics",
      },
      {
        key: "ambient_light",
        label: "Ambient Light",
        description: "Ambient/fill light",
        type: "text",
        placeholder: "e.g., dim ambient, bright fill, glowing atmosphere",
      },
      {
        key: "light_count",
        label: "Light Count",
        description: "Number of light sources",
        type: "text",
        placeholder: "e.g., single source, three-point, multiple",
      },
    ],
  },
  {
    key: "color_palette",
    label: "Color Palette",
    icon: "🎨",
    description: "Colors and tones",
    fields: [
      {
        key: "dominant_colors",
        label: "Dominant Colors",
        description: "Main colors in the image",
        type: "tags",
        placeholder: "Type a color and press Enter",
      },
      {
        key: "color_scheme_type",
        label: "Color Scheme",
        description: "Color harmony",
        type: "text",
        placeholder: "e.g., complementary, analogous, monochromatic, triadic",
      },
      {
        key: "saturation_level",
        label: "Saturation",
        description: "Color saturation",
        type: "text",
        placeholder: "e.g., highly saturated, muted, desaturated",
      },
      {
        key: "contrast_level",
        label: "Contrast",
        description: "Contrast level",
        type: "text",
        placeholder: "e.g., high contrast, low contrast, medium",
      },
      {
        key: "color_mood",
        label: "Color Mood",
        description: "Emotional color tone",
        type: "text",
        placeholder: "e.g., warm and inviting, cold and clinical, dark moody",
      },
      {
        key: "color_grading",
        label: "Color Grading",
        description: "Post color grading",
        type: "text",
        placeholder: "e.g., teal and orange, cross-processed, bleach bypass",
      },
      {
        key: "tonal_range",
        label: "Tonal Range",
        description: "Range of tones",
        type: "text",
        placeholder: "e.g., full range, high key, low key",
      },
    ],
  },
  {
    key: "artistic_style",
    label: "Artistic Style",
    icon: "🖌️",
    description: "Art medium and style references",
    fields: [
      {
        key: "medium",
        label: "Medium",
        description: "Artistic medium",
        type: "text",
        placeholder: "e.g., oil painting, photograph, 3D render, watercolor",
      },
      {
        key: "art_movement",
        label: "Art Movement",
        description: "Artistic movement",
        type: "text",
        placeholder: "e.g., impressionism, cyberpunk, art nouveau, surrealism",
      },
      {
        key: "style_reference",
        label: "Style Reference",
        description: "Reference artists or works",
        type: "textarea",
        placeholder: "e.g., Greg Rutkowski, Studio Ghibli, Blade Runner",
      },
      {
        key: "surface_texture",
        label: "Surface Texture",
        description: "Visual texture",
        type: "text",
        placeholder: "e.g., smooth render, oil paint strokes, grainy film",
      },
      {
        key: "rendering_style",
        label: "Rendering Style",
        description: "How it is rendered",
        type: "text",
        placeholder: "e.g., photorealistic, stylized, cel-shaded, flat",
      },
      {
        key: "level_of_abstraction",
        label: "Abstraction Level",
        description: "Realistic vs abstract",
        type: "text",
        placeholder: "e.g., hyperrealistic, semi-abstract, fully abstract",
      },
    ],
  },
  {
    key: "mood_atmosphere",
    label: "Mood & Atmosphere",
    icon: "🌫️",
    description: "Emotional tone and atmosphere",
    fields: [
      {
        key: "overall_mood",
        label: "Overall Mood",
        description: "General mood",
        type: "text",
        placeholder: "e.g., mysterious, joyful, melancholic, epic",
      },
      {
        key: "narrative_context",
        label: "Narrative Context",
        description: "Underlying story",
        type: "textarea",
        placeholder: "e.g., a lone warrior's last stand, a peaceful morning",
      },
      {
        key: "energy_level",
        label: "Energy Level",
        description: "Dynamic energy",
        type: "text",
        placeholder: "e.g., calm, dynamic, chaotic, serene",
      },
      {
        key: "atmosphere_effects",
        label: "Atmosphere Effects",
        description: "Atmospheric particles",
        type: "text",
        placeholder: "e.g., haze, smoke, dust particles, mist, fireflies",
      },
      {
        key: "emotional_tone",
        label: "Emotional Tone",
        description: "Emotional feel",
        type: "text",
        placeholder: "e.g., nostalgic, hopeful, dark, whimsical",
      },
    ],
  },
  {
    key: "material_texture",
    label: "Material & Texture",
    icon: "🧱",
    description: "Surface materials and textures",
    fields: [
      {
        key: "primary_material",
        label: "Primary Material",
        description: "Main material",
        type: "text",
        placeholder: "e.g., brushed metal, marble, wood, fabric",
      },
      {
        key: "secondary_material",
        label: "Secondary Material",
        description: "Additional material",
        type: "text",
        placeholder: "e.g., glass accents, gold trim, leather",
      },
      {
        key: "surface_finish",
        label: "Surface Finish",
        description: "Surface finish",
        type: "text",
        placeholder: "e.g., matte, glossy, satin, rough",
      },
      {
        key: "reflectivity",
        label: "Reflectivity",
        description: "How reflective",
        type: "text",
        placeholder: "e.g., non-reflective, mirror-like, subtle sheen",
      },
      {
        key: "transparency",
        label: "Transparency",
        description: "Transparency level",
        type: "text",
        placeholder: "e.g., opaque, translucent, transparent, frosted",
      },
      {
        key: "pattern_detail",
        label: "Pattern / Detail",
        description: "Surface patterns",
        type: "text",
        placeholder: "e.g., floral pattern, geometric, paisley, plain",
      },
      {
        key: "wear_aging",
        label: "Wear / Aging",
        description: "Age and wear",
        type: "text",
        placeholder: "e.g., vintage patina, brand new, weathered, rusted",
      },
    ],
  },
  {
    key: "technical_quality",
    label: "Technical Quality",
    icon: "⚡",
    description: "Resolution and detail settings",
    fields: [
      {
        key: "resolution_quality",
        label: "Resolution",
        description: "Output quality",
        type: "text",
        placeholder: "e.g., 4K, 8K, ultra HD, high resolution",
      },
      {
        key: "detail_level",
        label: "Detail Level",
        description: "Amount of detail",
        type: "text",
        placeholder: "e.g., highly detailed, intricate, ultra-fine, minimal",
      },
      {
        key: "sharpness",
        label: "Sharpness",
        description: "Image sharpness",
        type: "text",
        placeholder: "e.g., tack sharp, soft focus, selective sharp",
      },
      {
        key: "noise_grain",
        label: "Noise / Grain",
        description: "Film grain or noise",
        type: "text",
        placeholder: "e.g., clean, film grain, subtle noise",
      },
      {
        key: "render_engine",
        label: "Render Engine",
        description: "Rendering engine",
        type: "text",
        placeholder: "e.g., Octane, Unreal Engine 5, V-Ray, Blender",
      },
    ],
  },
  {
    key: "camera_lens",
    label: "Camera & Lens",
    icon: "📷",
    description: "Camera and lens settings",
    fields: [
      {
        key: "lens_type",
        label: "Lens Type",
        description: "Camera lens",
        type: "text",
        placeholder: "e.g., 85mm portrait, 24mm wide, 50mm standard, macro",
      },
      {
        key: "aperture",
        label: "Aperture",
        description: "Aperture value",
        type: "text",
        placeholder: "e.g., f/1.4, f/2.8, f/8, f/16",
      },
      {
        key: "shutter_speed_effect",
        label: "Shutter Speed Effect",
        description: "Motion effect",
        type: "text",
        placeholder: "e.g., frozen action, motion blur, long exposure trails",
      },
      {
        key: "iso_effect",
        label: "ISO Effect",
        description: "ISO noise effect",
        type: "text",
        placeholder: "e.g., clean low ISO, grainy high ISO",
      },
      {
        key: "film_stock",
        label: "Film Stock",
        description: "Film emulation",
        type: "text",
        placeholder: "e.g., Kodak Portra 400, Fuji Velvia 50, Ilford HP5",
      },
      {
        key: "filter_on_lens",
        label: "Lens Filter",
        description: "Physical filter",
        type: "text",
        placeholder: "e.g., polarizer, ND filter, star filter, soft focus",
      },
    ],
  },
  {
    key: "post_processing",
    label: "Post Processing",
    icon: "🔧",
    description: "Post-production effects",
    fields: [
      {
        key: "vignette",
        label: "Vignette",
        description: "Edge darkening",
        type: "text",
        placeholder: "e.g., subtle vignette, heavy vignette, none",
      },
      {
        key: "bloom_glow",
        label: "Bloom / Glow",
        description: "Highlight bloom",
        type: "text",
        placeholder: "e.g., soft bloom, neon glow, none",
      },
      {
        key: "chromatic_aberration",
        label: "Chromatic Aberration",
        description: "Color fringing",
        type: "text",
        placeholder: "e.g., subtle CA, heavy, none",
      },
      {
        key: "lens_distortion",
        label: "Lens Distortion",
        description: "Lens distortion",
        type: "text",
        placeholder: "e.g., barrel, pincushion, none",
      },
      {
        key: "color_filter",
        label: "Color Filter",
        description: "Color filter overlay",
        type: "text",
        placeholder: "e.g., vintage warm, cool blue, sepia, none",
      },
      {
        key: "grain_overlay",
        label: "Grain Overlay",
        description: "Added grain effect",
        type: "text",
        placeholder: "e.g., 35mm film grain, digital noise, none",
      },
      {
        key: "sharpening",
        label: "Sharpening",
        description: "Sharpening level",
        type: "text",
        placeholder: "e.g., strong sharpening, subtle, none",
      },
    ],
  },
  {
    key: "negative_prompt",
    label: "Negative Prompt",
    icon: "🚫",
    description: "Elements to avoid in the image",
    fields: [
      {
        key: "avoid_elements",
        label: "Avoid Elements",
        description: "Things to exclude",
        type: "tags",
        placeholder: "e.g., watermark, text, border",
      },
      {
        key: "avoid_styles",
        label: "Avoid Styles",
        description: "Styles to avoid",
        type: "tags",
        placeholder: "e.g., cartoon, anime, pixel art",
      },
      {
        key: "avoid_artifacts",
        label: "Avoid Artifacts",
        description: "AI artifacts to avoid",
        type: "tags",
        placeholder: "e.g., extra fingers, bad anatomy",
      },
      {
        key: "avoid_quality",
        label: "Avoid Quality Issues",
        description: "Quality issues to avoid",
        type: "tags",
        placeholder: "e.g., blurry, low resolution, noisy",
      },
    ],
  },
  {
    key: "generation_params",
    label: "Generation Parameters",
    icon: "⚙️",
    description: "Technical generation settings (not included in prompt text)",
    fields: [
      {
        key: "aspect_ratio",
        label: "Aspect Ratio",
        description: "Image aspect ratio",
        type: "text",
        placeholder: "e.g., 16:9, 1:1, 9:16, 4:3",
      },
      {
        key: "seed",
        label: "Seed",
        description: "Random seed for reproducibility",
        type: "number",
        placeholder: "Leave empty for random",
      },
      {
        key: "steps",
        label: "Steps",
        description: "Generation steps",
        type: "number",
        placeholder: "e.g., 20, 30, 50",
      },
      {
        key: "cfg_scale",
        label: "CFG Scale",
        description: "Classifier-free guidance",
        type: "number",
        placeholder: "e.g., 7.0, 7.5, 12.0",
      },
      {
        key: "sampler",
        label: "Sampler",
        description: "Sampling method",
        type: "text",
        placeholder: "e.g., DPM++ 2M Karras, Euler a",
      },
      {
        key: "model_recommendation",
        label: "Recommended Model",
        description: "Suggested AI model",
        type: "text",
        placeholder: "e.g., SDXL, Midjourney v6, DALL-E 3",
      },
    ],
  },
];
