"use client";

import Link from "next/link";
import { Download, ExternalLink, Focus, Paintbrush, Scan } from "lucide-react";
import { useEffect, useState } from "react";
import type { WorkspaceAsset } from "@/components/studio/ToolInspector";

export default function AssetCanvas({ assets, selectedIndex, onSelect, projectId, onEmptyFocus, loadingCount = 0 }: { assets: WorkspaceAsset[]; selectedIndex: number; onSelect: (index: number) => void; projectId: string; onEmptyFocus: () => void; loadingCount?: number }) {
  const selected = assets[selectedIndex] ?? null;
  const [actualSize, setActualSize] = useState(false);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "ArrowLeft" && assets.length) onSelect((selectedIndex - 1 + assets.length) % assets.length); if (event.key === "ArrowRight" && assets.length) onSelect((selectedIndex + 1) % assets.length); if (event.key === "Escape") setActualSize(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [assets.length, onSelect, selectedIndex]);
  return <div className="relative flex min-h-0 flex-1 flex-col overflow-hidden">
    <div className="checker-stage relative min-h-0 flex-1 overflow-auto p-4 sm:p-8">
      {!selected && loadingCount > 0 && <div className="flex h-full min-h-[300px] items-center justify-center gap-3" aria-label="Generating images"><span className="flex size-16 items-center justify-center rounded-xl border border-white/10 bg-white/[0.04]"><Scan className="size-6 animate-pulse text-[#a995ff]" /></span><span className="text-sm text-[#98a2b3]">Đang tạo {loadingCount} ảnh…</span></div>}
      {selected?.signedUrl ? <div className="flex h-full min-h-[300px] items-center justify-center"><img src={selected.signedUrl} alt={selected.name} className={actualSize ? "max-w-none" : "max-h-full max-w-full object-contain"} /></div> : !selected && <button onClick={onEmptyFocus} className="flex h-full min-h-[340px] w-full flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-[#7c5cff]/10 text-[#a995ff]"><Scan className="size-7" /></span><h2 className="mt-5 text-xl font-semibold">Start with a prompt</h2><p className="mt-2 max-w-md px-5 text-sm leading-6 text-[#98a2b3]">Describe an image below. Generated results will appear here without leaving the workspace.</p></button>}
      {selected && <div className="absolute left-1/2 top-3 flex -translate-x-1/2 items-center gap-1 rounded-xl border border-white/10 bg-[#111419]/90 p-1 shadow-xl backdrop-blur"><button className={`studio-icon-button size-9 min-h-9 ${!actualSize ? "bg-[#7c5cff]/25 text-white" : ""}`} onClick={() => setActualSize(false)} aria-label="Zoom to fit" aria-pressed={!actualSize} title="Zoom to fit"><Focus className="size-4" /></button><button className={`studio-icon-button size-9 min-h-9 ${actualSize ? "bg-[#7c5cff]/25 text-white" : ""}`} onClick={() => setActualSize(true)} aria-label="View at 100 percent" aria-pressed={actualSize} title="100%"><span className="text-[11px] font-semibold">100%</span></button>{selected.signedUrl && <a className="studio-icon-button size-9 min-h-9" href={selected.signedUrl} download aria-label="Download image" title="Download"><Download className="size-4" /></a>}<Link className="studio-icon-button size-9 min-h-9" href={`/projects/${projectId}/assets/${selected.id}`} aria-label="Open asset details" title="Details"><ExternalLink className="size-4" /></Link></div>}
    </div>
    {assets.length > 0 && <div className="shrink-0 overflow-x-auto border-t border-white/10 bg-[#111419] p-3"><div className="flex min-w-max gap-2">{assets.map((asset, index) => <button key={`${asset.id}-${asset.signedUrl}`} onClick={() => onSelect(index)} aria-label={`Select ${asset.name}`} className={`min-h-0 overflow-hidden rounded-xl border-2 ${index === selectedIndex ? "border-[#7c5cff]" : "border-transparent"}`}>{asset.signedUrl ? <img src={asset.signedUrl} alt="" className="size-16 object-cover sm:size-20" /> : <span className="flex size-16 items-center justify-center bg-white/[0.04] text-xs text-[#667085] sm:size-20">Empty</span>}</button>)}{Array.from({ length: loadingCount }, (_, index) => <span key={`loading-${index}`} aria-hidden className="size-16 animate-pulse rounded-xl border border-white/10 bg-white/[0.04] sm:size-20" />)}</div></div>}
  </div>;
}
